### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by HarveyPlante** [HarveyPlante/codelab-css-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://entertaining-flavor.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/css-intro/1) criteria:
- [x] Include at least one instance of the `margin` property.
- [x] Include at least one instance of the `padding` property.
- [x] Include at least one instance of the `border` property.
- [x] Include at least one instance of the `color` property.
- [x] Include at least one instance of the `background` property.
- [x] Include at least one instance of the `font-size` property.
- [x] Include at least one instance of the `line-height` property.
- [x] All properties must have a visible effect.
- [x] Return no errors (warnings are OK) when the HTML document is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] Return no errors (warnings are OK) when contents of your CSS are pasted into [CSS Lint](http://csslint.net/)

**Comment by chrisvfritz** [comment]
Looking good! We've even got some nice `text-shadow` in here! 🎉  There are just a few areas for improvement I see and most of them are really quick fixes. 😃 

### surge URL not working

I'm seeing the same surge problem as in [the other project](https://github.com/HarveyPlante/codelab-js-intro/issues/1#issuecomment-216872364).

### A lot of unnecessary empty lines

Could we delete some of the empty lines here? It's OK to leave a single empty line sometimes if it makes the code more readable, but there generally should never be more than one empty line in a row and even a single empty line should be used sparingly. The reason is to just make the code easier to skim.

### Indentation inconsistencies in CSS

In CSS, a good general rule is to indent properties inside of a CSS rule exactly 2 spaces. So this for example:

``` css
body {
  background-color: lightblue;
  padding: 20px 10px;
 font-family: Comic Sans MS;
 max-width: 2000px;
 margin: 4 auto;
 font-size: 1.4em


}
```

Could be updated to:

``` css
body {
  background-color: lightblue;
  padding: 20px 10px;
  font-family: Comic Sans MS;
  max-width: 2000px;
  margin: 4 auto;
  font-size: 1.4em
}
```

Try to apply that kind of indentation consistently through the rest of your CSS.

### Closing tags can be on same line

For some elements, it looks like [the closing tags](https://github.com/HarveyPlante/codelab-css-intro/blob/master/resume.html#L138) are one a separate line, even though the initial tag and all the contents are on the previous line. I would consolidate and join the closing tag together into the one line.

### `line-height: normal` doesn't really do anything here

Try adjusting `line-height` to a unitless value, such as `line-height: 1`, `line-height: 2`, or `line-height: 1.5`. With those values, it'll work like line spacing in Word, where `1` is single spaced, `2` is double spaced, etc.
